### ISSUE TITLE
Prop is Stuck in/on Person when adding new props

### ISSUE THREAD

**Issue by shoxylein** [uniqscripts/uniq_vendingmachine#1]
Prop is Stuck in/on Person when addin new props 

see medal clip ->https://medal.tv/games/gta-v/clips/1BUtZ6pCVf-bAP/d1337x6iyB4m?invite=cr-MSxIZTUsMjY5NjY1NDMs

**Comment by katotekii** [comment]
download new and try

**Comment by shoxylein** [comment]
> download new and try

nope > https://prnt.sc/w3Sn5ZWd7B_1 now it gives an error

**Comment by katotekii** [comment]
works fine to me

**Comment by shoxylein** [comment]
RegisterNetEvent('uniq_vending:startCreating', function(players)
    if source == '' then return end
    local vending = {}

    table.sort(players, function (a, b)
  -> This it has a problem with      return a.id < b.id
    end)

    local input = lib.inputDialog(L('input.vending_creator'), {
        { type = 'input', label = L('input.vending_label'), required = true },
        { type = 'number', label = L('input.vending_price'), required = true, min = 1 },
        { type = 'select', label = L('input.select_object'), required = true, options = cfg.Machines, clearable = true },
        { type = 'select', label = L('input.owned_type.title'), options = {
            { label = L('input.owned_type.a'), value = 'a' },
            { label = L('input.owned_type.b'), value = 'b' },
        }, clearable = true, required = true },
        { type = 'checkbox', label = L('input.blip'), checked = true }
    })

    if not input then return end

    if input[5] then
        local blip = lib.inputDialog('', {
            { type = 'number', label = L('input.blipInput.a'), required = true },
            { type = 'number', label = L('input.blipInput.b'), required = true, precision = true, min = 0 },
            { type = 'number', label = L('input.blipInput.c'), required = true },
            { type = 'input',  label = L('input.blipInput.d'), required = true, default = input[1] },
        })

        if not blip then return end

        vending.blip = {
            sprite = blip[1],
            scale = blip[2],
            colour = blip[3],
            name = blip[4],
        }
    end

**Comment by shoxylein** [comment]
Okay, this worked after a restart, but i still can't move he object around

**Comment by katotekii** [comment]
move somewhere where there are no objects (e.g airport) to figure out how the object placer works

**Comment by shoxylein** [comment]
So now it is supper laggy and whenever i press enter it spawn's 2 props 

see -> https://medal.tv/games/gta-v/clips/1BZ7soHeWGUZhk/d1337k2u91aC?invite=cr-MSxhQTUsMjY5NjY1NDMs

**Comment by shoxylein** [comment]
and whenever i click access vending it says in You cannot open this inventory

**Comment by katotekii** [comment]
could be object, as for `You cannot open this inventory` not sure what version of ox inv you have, script works as shown in showcase

**Comment by shoxylein** [comment]
what does could be object mean?, i use version 2.30 with a redesign

**Comment by katotekii** [comment]
means try default object that we provided in cofnig

**Comment by shoxylein** [comment]
Okay, updated ox_inv and it needed a restart now it does not lagg anymore but still can't open vending inv

**Comment by katotekii** [comment]
inv or shop?

**Comment by shoxylein** [comment]
both i think
