### ISSUE TITLE
Dispensers for placeable OBJECTS

### ISSUE THREAD

**Issue by SamBradley123** [uniqscripts/uniq_vendingmachine#2]
Good morning !
Great storyline!

Would it be possible instead of having a menu which places the distributors, but to have ITEMS that we buy, which we place, and the one who places these items becomes the owner of the distributors?

**Comment by isgrandson** [comment]
Since it is an open source resource, you can modify it however you want.
Our team does not have enough time to please everyone and fulfill their wishes.
If several people have the same wish, we will take it into consideration.
