### ISSUE TITLE
Error while trying to spawn command

### ISSUE THREAD

**Issue by ChaseBacon** [uniqscripts/uniq_vendingmachine#3]
Getting SCRIPT ERROR: @uniq_vendingmachine/client/main.lua:282: attempt to compare two nil values

Any help please?

**Comment by katotekii** [comment]
framework ?

**Comment by ChaseBacon** [comment]
QB

**Comment by katotekii** [comment]
download https://github.com/uniqscripts/uniq_vendingmachine/releases/tag/1.2.0 and try

**Comment by ChaseBacon** [comment]
ok that has it working, but one mor thing   when i tried to sell machine it stays there,   is there any way to pick it up or remove it?

**Comment by katotekii** [comment]
via admin command `dellvending`

**Comment by ChaseBacon** [comment]
also now the errors i have are this

https://i.imgur.com/uHkzP5m.jpeg

**Comment by katotekii** [comment]
you now have 2 same scripts running -,-

**Comment by ChaseBacon** [comment]
yea im about to reboot and see what happens

**Comment by ChaseBacon** [comment]
works good now, however placement is laggy other than that perfect

**Comment by ChaseBacon** [comment]
also do you ever plan on giving it the option of using target?

**Comment by katotekii** [comment]
its open source so you can do whatever you want
